# Generated by Django 4.2.2 on 2023-06-16 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 15, 13, 39, 589042)),
        ),
    ]
