# Generated by Django 4.1.5 on 2023-06-16 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_detalleventa_venta_alter_venta_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 16, 16, 16, 17, 198298)
            ),
        ),
    ]
